# Generated by Django 4.2.21 on 2025-06-03 10:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], default=app.models.CategoryType['POSITIVE'], max_length=15)),
                ('items', models.ManyToManyField(auto_created=True, to='app.item')),
            ],
        ),
    ]
