# Generated by Django 4.2.21 on 2025-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
